name: CI ArticlesApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4 # Version 4 est plus stable

      - name: ğŸŸ¢ Setup Node
        uses: actions/setup-node@v4 # Version 4
        with:
          node-version: 18
          cache: 'npm' # Ajoute du cache pour accÃ©lÃ©rer l'installation

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ” Run Linter
        run: npm run lint || echo "Linter failed but continuing..."

      - name: ğŸ§ª Run Tests
        run: npm test